# https://embarkstudios.github.io/cargo-deny

[graph]
all-features = true
targets = ["aarch64-apple-darwin", "wasm32-wasip2"]

[output]
feature-depth = 1

[advisories]
unmaintained = 'workspace'
# ignore = [
#   "RUSTSEC-2024-0445",
# ]

[licenses]
allow = [
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "OpenSSL",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
  "Zlib",
]

[licenses.private]
ignore = true

[[licenses.clarify]]
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name = "ring"

[bans]
deny = [
  { name = "tokio", deny-multiple-versions = true },
]
multiple-versions = "allow"
skip = []
skip-tree = []
wildcards = "allow"

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "warn"

