[registries]
credibil = { index = "sparse+https://pkgs.dev.azure.com/credibil/_packaging/credibil/Cargo/index/" }

[registry]
global-credential-providers = [
  "cargo:macos-keychain",
  "cargo:token",
  # "cargo-credential-1password --account credibil.1password.com --vault Credibil",
]
